#!/bin/sh /etc/rc.common

START=99

start()
{
	echo "---- MY APP START ----"
	alsactl init
	modprobe gpio-mpc8xxx
	screen -m -d python3 webservice.py 
	screen -m -d python3 music_player.py
}        
         
restart()
{    
	echo "---- MY APP START ----"
	alsactl init
	modprobe gpio-mpc8xxx
	screen -m -d python3 webservice.py 
	screen -m -d python3 music_player.py
}
    

